# Generated by Django 4.1.5 on 2023-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(default=None),
        ),
    ]
